name: Start Discord Bot

on:
  workflow_dispatch:

jobs:
  launch_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run the app with secret
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}   # Inject secret as environment variable
        run: node index.js
